package:
  name: ros-galactic-rviz-visual-testing-framework
  version: 8.5.1
source:
  git_url: https://github.com/ros2-gbp/rviz-release.git
  git_rev: release/galactic/rviz_visual_testing_framework/8.5.1-1
  folder: ros-galactic-rviz-visual-testing-framework/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - python
    - qt-main
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-cppcheck
    - ros-galactic-ament-cmake-cpplint
    - ros-galactic-ament-cmake-gmock
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-cmake-lint-cmake
    - ros-galactic-ament-cmake-uncrustify
    - ros-galactic-ament-cmake-xmllint
    - ros-galactic-ament-lint-auto
    - ros-galactic-rcutils
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rviz-common
    - ros2-distro-mutex 0.2 galactic
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-rcutils
    - ros-galactic-ros-workspace
    - ros-galactic-rviz-common
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
