package:
  name: ros-galactic-tf2-ros-py
  version: 0.17.4
source:
  git_url: https://github.com/ros2-gbp/geometry2-release.git
  git_rev: release/galactic/tf2_ros_py/0.17.4-1
  folder: ros-galactic-tf2-ros-py/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pytest
    - python
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-sensor-msgs
    - ros2-distro-mutex 0.2 galactic
    - setuptools
  run:
    - python
    - ros-galactic-geometry-msgs
    - ros-galactic-rclpy
    - ros-galactic-ros-workspace
    - ros-galactic-std-msgs
    - ros-galactic-tf2-msgs
    - ros-galactic-tf2-py
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
