package:
  name: ros2-distro-mutex
  version: 0.1.0

build:
  number: 0
  string: galactic
  run_exports:
    # NOTE MANUALLY EDIT THIS!!!!
    - ros2-distro-mutex 0.1 galactic

requirements:
  # NOTE:
  # The idea with automatically adding versions to run_exports doesn't
  # work since we don't want all these dependencies as run deps of all ROS
  # packages. Therefore I am currently manually adding them to run_constrained.
  # This has to be synchronized with our current conda_build_config all the time :(
  # host:
  #   # values here should 
  #   - boost-cpp
  #   - log4cxx
  #   - poco
  #   - pcl
  #   - opencv
  #   - gazebo
  #   - ogre
  #   - qt
  # run:
  # values here should be applied from run_exports!
  # if the upstream package does not have run_exports
  # please change it in the conda_build_config.yaml!
  run_constrained:
    - boost-cpp 1.74
    - log4cxx 0.11
    - pcl 1.11
    - libopencv 4.5.2
    - poco 1.10
    - gazebo 11
    - ogre 1.12
    - libpqxx 6

about:
  home: https://github.com/robostack/ros-galactic
  license: BSD-3-Clause
  summary: |
    The ROS2 distro mutex. To switch between ROS2 versions, you need to change the mutex.
    E.g. mamba install ros2-distro-mutex=*=galactic to switch to galactic.

extra:
  recipe-maintainers:
    - ros-forge
