package:
  name: ros-galactic-rosbridge-library
  version: 1.3.0
source:
  git_url: https://github.com/ros2-gbp/rosbridge_suite-release.git
  git_rev: release/galactic/rosbridge_library/1.3.0-1
  folder: ros-galactic-rosbridge-library/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pillow
    - pymongo
    - python
    - ros-galactic-actionlib-msgs
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-pytest
    - ros-galactic-ament-cmake-ros
    - ros-galactic-builtin-interfaces
    - ros-galactic-diagnostic-msgs
    - ros-galactic-example-interfaces
    - ros-galactic-geometry-msgs
    - ros-galactic-nav-msgs
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-sensor-msgs
    - ros-galactic-std-msgs
    - ros-galactic-std-srvs
    - ros-galactic-stereo-msgs
    - ros-galactic-tf2-msgs
    - ros-galactic-trajectory-msgs
    - ros-galactic-visualization-msgs
    - ros2-distro-mutex 0.2 galactic
  run:
    - pillow
    - pymongo
    - python
    - ros-galactic-rclpy
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-runtime
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
