package:
  name: ros-galactic-dwb-core
  version: 1.0.12
source:
  git_url: https://github.com/SteveMacenski/navigation2-release.git
  git_rev: release/galactic/dwb_core/1.0.12-1
  folder: ros-galactic-dwb-core/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-dwb-msgs
    - ros-galactic-geometry-msgs
    - ros-galactic-nav-2d-msgs
    - ros-galactic-nav-2d-utils
    - ros-galactic-nav-msgs
    - ros-galactic-nav2-common
    - ros-galactic-nav2-core
    - ros-galactic-nav2-costmap-2d
    - ros-galactic-nav2-util
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-sensor-msgs
    - ros-galactic-std-msgs
    - ros-galactic-tf2-ros
    - ros-galactic-visualization-msgs
    - ros2-distro-mutex 0.2 galactic
  run:
    - python
    - ros-galactic-dwb-msgs
    - ros-galactic-geometry-msgs
    - ros-galactic-nav-2d-utils
    - ros-galactic-nav-msgs
    - ros-galactic-nav2-core
    - ros-galactic-nav2-costmap-2d
    - ros-galactic-nav2-util
    - ros-galactic-pluginlib
    - ros-galactic-rclcpp
    - ros-galactic-ros-workspace
    - ros-galactic-std-msgs
    - ros-galactic-tf2-ros
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
