package:
  name: ros-galactic-ros2lifecycle
  version: 0.13.4
source:
  git_url: https://github.com/ros2-gbp/ros2cli-release.git
  git_rev: release/galactic/ros2lifecycle/0.13.4-1
  folder: ros-galactic-ros2lifecycle/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 2
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pytest
    - python
    - ros-galactic-ament-copyright
    - ros-galactic-ament-flake8
    - ros-galactic-ament-pep257
    - ros-galactic-ament-xmllint
    - ros-galactic-rclpy
    - ros-galactic-ros-environment
    - ros-galactic-ros-testing
    - ros-galactic-ros-workspace
    - ros-galactic-ros2cli
    - ros-galactic-ros2lifecycle-test-fixtures
    - ros2-distro-mutex 0.2 galactic
    - setuptools
  run:
    - python
    - ros-galactic-lifecycle-msgs
    - ros-galactic-rclpy
    - ros-galactic-ros-workspace
    - ros-galactic-ros2cli
    - ros-galactic-ros2node
    - ros-galactic-ros2service
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
