package:
  name: ros-galactic-rclcpp
  version: 9.2.1
source:
  git_url: https://github.com/ros2-gbp/rclcpp-release.git
  git_rev: release/galactic/rclcpp/9.2.1-1
  folder: ros-galactic-rclcpp/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - python
    - ros-galactic-ament-cmake-gmock
    - ros-galactic-ament-cmake-google-benchmark
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-cmake-ros
    - ros-galactic-ament-index-cpp
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-builtin-interfaces
    - ros-galactic-libstatistics-collector
    - ros-galactic-mimick-vendor
    - ros-galactic-performance-test-fixture
    - ros-galactic-rcl
    - ros-galactic-rcl-interfaces
    - ros-galactic-rcl-yaml-param-parser
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-rmw
    - ros-galactic-rmw-implementation-cmake
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosgraph-msgs
    - ros-galactic-rosidl-default-generators
    - ros-galactic-rosidl-runtime-cpp
    - ros-galactic-rosidl-typesupport-c
    - ros-galactic-rosidl-typesupport-cpp
    - ros-galactic-statistics-msgs
    - ros-galactic-test-msgs
    - ros-galactic-tracetools
    - ros2-distro-mutex 0.2 galactic
  run:
    - python
    - ros-galactic-ament-index-cpp
    - ros-galactic-builtin-interfaces
    - ros-galactic-libstatistics-collector
    - ros-galactic-rcl
    - ros-galactic-rcl-interfaces
    - ros-galactic-rcl-yaml-param-parser
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-rmw
    - ros-galactic-ros-workspace
    - ros-galactic-rosgraph-msgs
    - ros-galactic-rosidl-runtime-cpp
    - ros-galactic-rosidl-typesupport-c
    - ros-galactic-rosidl-typesupport-cpp
    - ros-galactic-statistics-msgs
    - ros-galactic-tracetools
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
