package:
  name: ros-galactic-nav2-map-server
  version: 1.0.12
source:
  git_url: https://github.com/SteveMacenski/navigation2-release.git
  git_rev: release/galactic/nav2_map_server/1.0.12-1
  folder: ros-galactic-nav2-map-server/src/work
  patches:
    - patch/ros-galactic-nav2-map-server.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - graphicsmagick
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-cmake-pytest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-launch
    - ros-galactic-launch-ros
    - ros-galactic-launch-testing
    - ros-galactic-nav-msgs
    - ros-galactic-nav2-common
    - ros-galactic-nav2-msgs
    - ros-galactic-nav2-util
    - ros-galactic-rclcpp
    - ros-galactic-rclcpp-lifecycle
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-std-msgs
    - ros-galactic-tf2
    - ros-galactic-yaml-cpp-vendor
    - ros2-distro-mutex 0.2 galactic
  run:
    - graphicsmagick
    - python
    - ros-galactic-launch-ros
    - ros-galactic-launch-testing
    - ros-galactic-nav-msgs
    - ros-galactic-nav2-msgs
    - ros-galactic-nav2-util
    - ros-galactic-rclcpp
    - ros-galactic-rclcpp-lifecycle
    - ros-galactic-ros-workspace
    - ros-galactic-std-msgs
    - ros-galactic-tf2
    - ros-galactic-yaml-cpp-vendor
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
