package:
  name: ros-galactic-rcl-yaml-param-parser
  version: 3.1.3
source:
  git_url: https://github.com/ros2-gbp/rcl-release.git
  git_rev: release/galactic/rcl_yaml_param_parser/3.1.3-1
  folder: ros-galactic-rcl-yaml-param-parser/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-cmake-ros
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-libyaml-vendor
    - ros-galactic-mimick-vendor
    - ros-galactic-osrf-testing-tools-cpp
    - ros-galactic-performance-test-fixture
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-rmw
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.2 galactic
    - yaml
    - yaml-cpp
  run:
    - python
    - ros-galactic-libyaml-vendor
    - ros-galactic-rmw
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.2 galactic
    - yaml
    - yaml-cpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
