package:
  name: ros-galactic-rcl-logging-spdlog
  version: 2.1.4
source:
  git_url: https://github.com/ros2-gbp/rcl_logging-release.git
  git_rev: release/galactic/rcl_logging_spdlog/2.1.4-1
  folder: ros-galactic-rcl-logging-spdlog/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake-ros
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-performance-test-fixture
    - ros-galactic-rcl-logging-interface
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-spdlog-vendor
    - ros2-distro-mutex 0.2 galactic
    - spdlog
  run:
    - python
    - ros-galactic-rcl-logging-interface
    - ros-galactic-rcpputils
    - ros-galactic-rcutils
    - ros-galactic-ros-workspace
    - ros-galactic-spdlog-vendor
    - ros2-distro-mutex 0.2 galactic
    - spdlog
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
