package:
  name: ros-galactic-navigation2
  version: 1.0.12
source:
  git_url: https://github.com/SteveMacenski/navigation2-release.git
  git_rev: release/galactic/navigation2/1.0.12-1
  folder: ros-galactic-navigation2/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.2 galactic
  run:
    - python
    - ros-galactic-nav2-amcl
    - ros-galactic-nav2-behavior-tree
    - ros-galactic-nav2-bt-navigator
    - ros-galactic-nav2-controller
    - ros-galactic-nav2-core
    - ros-galactic-nav2-costmap-2d
    - ros-galactic-nav2-dwb-controller
    - ros-galactic-nav2-lifecycle-manager
    - ros-galactic-nav2-map-server
    - ros-galactic-nav2-msgs
    - ros-galactic-nav2-navfn-planner
    - ros-galactic-nav2-planner
    - ros-galactic-nav2-recoveries
    - ros-galactic-nav2-regulated-pure-pursuit-controller
    - ros-galactic-nav2-rotation-shim-controller
    - ros-galactic-nav2-rviz-plugins
    - ros-galactic-nav2-smac-planner
    - ros-galactic-nav2-theta-star-planner
    - ros-galactic-nav2-util
    - ros-galactic-nav2-voxel-grid
    - ros-galactic-nav2-waypoint-follower
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
