package:
  name: ros-galactic-rosbridge-suite
  version: 1.3.0
source:
  git_url: https://github.com/ros2-gbp/rosbridge_suite-release.git
  git_rev: release/galactic/rosbridge_suite/1.3.0-1
  folder: ros-galactic-rosbridge-suite/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 3
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake-core
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.2 galactic
  run:
    - python
    - ros-galactic-ros-workspace
    - ros-galactic-rosapi
    - ros-galactic-rosbridge-library
    - ros-galactic-rosbridge-server
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
