package:
  name: ros-galactic-rosidl-generator-cpp
  version: 2.2.2
source:
  git_url: https://github.com/ros2-gbp/rosidl-release.git
  git_rev: release/galactic/rosidl_generator_cpp/2.2.2-1
  folder: ros-galactic-rosidl-generator-cpp/src/work
  patches:
    - patch/ros-galactic-rosidl-generator-cpp.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-core
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-cmake
    - ros-galactic-rosidl-generator-c
    - ros-galactic-rosidl-runtime-c
    - ros-galactic-rosidl-runtime-cpp
    - ros-galactic-test-interface-files
    - ros2-distro-mutex 0.2 galactic
  run:
    - python
    - ros-galactic-ament-cmake-core
    - ros-galactic-ament-index-python
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-cli
    - ros-galactic-rosidl-cmake
    - ros-galactic-rosidl-generator-c
    - ros-galactic-rosidl-parser
    - ros2-distro-mutex 0.2 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
